/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    orders: Order;
    customers: Customer;
    media: Media;
    'pro-members': ProMember;
    'promo-codes': PromoCode;
    'customer-files': CustomerFile;
    'push-sequences': PushSequence;
    'offer-config': OfferConfig;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'pro-members': ProMembersSelect<false> | ProMembersSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    'customer-files': CustomerFilesSelect<false> | CustomerFilesSelect<true>;
    'push-sequences': PushSequencesSelect<false> | PushSequencesSelect<true>;
    'offer-config': OfferConfigSelect<false> | OfferConfigSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('it' | 'en' | 'de' | 'fr' | 'es')
    | ('it' | 'en' | 'de' | 'fr' | 'es')[];
  globals: {};
  globalsSelect: {};
  locale: 'it' | 'en' | 'de' | 'fr' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Es. foglio-pelle-tattoo — solo minuscole e trattini
   */
  slug: string;
  section: 'tattoo' | 'pmu';
  /**
   * Se disattivato, il prodotto non appare nelle griglie ma rimane accessibile via URL diretto e nei kit.
   */
  active?: boolean | null;
  limitedStock?: boolean | null;
  /**
   * Numero piu basso = appare prima
   */
  order?: number | null;
  /**
   * Attiva per prodotti che vengono lavorati dopo l'acquisto. Mostra tempi di produzione + spedizione.
   */
  madeToOrder?: boolean | null;
  /**
   * Giorni lavorativi per produrre il pezzo (solo su ordinazione)
   */
  productionDays?: number | null;
  /**
   * Giorni lavorativi dalla spedizione alla consegna
   */
  shippingDays?: number | null;
  /**
   * Max 120 caratteri — appare nella card prodotto
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Testo che sottolinea unicita artigianale. Es: "Non avrai mai due ordini con la stessa pelle."
   */
  uniqueNote?: string | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Video demo del prodotto (MP4 o WebM, max 50MB). Appaiono prima delle immagini nella gallery.
   */
  videos?:
    | {
        video: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Prezzo del formato piu piccolo/entry. Le varianti hanno prezzi specifici.
   */
  basePrice: number;
  /**
   * Mostra questo prodotto nel portale rivenditori
   */
  resellerVisible?: boolean | null;
  /**
   * Sconto % per fascia di quantità. Lascia vuoto per non applicare sconti rivenditori.
   */
  priceTiers?:
    | {
        minQty: number;
        maxQty?: number | null;
        discountPercent: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Ogni riga = un formato disponibile (A5, A4, XXL). Ogni variante ha il suo prezzo.
   */
  variants?:
    | {
        /**
         * Es. FP-A5, FP-A4, FP-XXL
         */
        sku: string;
        /**
         * Es. "A5", "A4", "XXL"
         */
        label: string;
        price: number;
        stockStatus?: ('available' | 'low' | 'unavailable') | null;
        /**
         * Mostra "X pezzi rimasti" se compilato
         */
        limitedQty?: number | null;
        /**
         * Se presente, viene mostrata al posto delle immagini prodotto quando il cliente seleziona questa variante.
         */
        image?: (number | null) | Media;
        /**
         * Appare sotto i bottoni variante quando il cliente seleziona questa. Es: "Stai per acquistare un foglio 30×20×4mm — il formato ideale per braccia e gambe."
         */
        description?: string | null;
        /**
         * Es. "30x20 cm"
         */
        dimensions?: string | null;
        thicknessMm?: number | null;
        /**
         * Se vuoto, tutte le combinazioni sono disponibili. Se popolato, solo queste combinazioni sono acquistabili.
         */
        validCombinations?:
          | {
              texture?: string | null;
              colore?: string | null;
              spessore?: string | null;
              stencil?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Es: texture, colore, spessore. NON modificano il prezzo.
   */
  attributes?:
    | {
        /**
         * Es: texture, colore, spessore — usa solo lettere minuscole e trattini
         */
        name: string;
        /**
         * Es: "Texture", "Colore", "Spessore"
         */
        label: string;
        options: {
          /**
           * Es: liscia, ruvida, naturale, 4mm
           */
          value: string;
          /**
           * Es: "Liscia", "Ruvida", "Naturale", "4mm"
           */
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * 4 card che spiegano perche scegliere questo prodotto. Se vuoto, vengono usati i default.
   */
  featureHighlights?:
    | {
        icon: 'sparkles' | 'shield' | 'star' | 'truck';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 3 step guidati per l utilizzo del prodotto. Se vuoto, viene usato il default.
   */
  usageSteps?:
    | {
        /**
         * Es: 01, 02, 03
         */
        step: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Prodotti che compongono questo kit. Appariranno nella pagina prodotto con il loro prezzo e un tasto "Aggiungi al carrello".
   */
  components?: (number | Product)[] | null;
  /**
   * Offerte bundle con sconto. Es: "3 fogli -10%". Appaiono come cards di upsell sulla pagina prodotto.
   */
  packs?:
    | {
        /**
         * Es: "Starter Kit", "Pro Bundle"
         */
        name: string;
        /**
         * Quanti pezzi include il pack
         */
        quantity: number;
        /**
         * Es: 10 = 10% di sconto sul prezzo unitario × quantità
         */
        discountPercent: number;
        /**
         * Es: "Più venduto", "Miglior valore" — appare come tag colorato sulla card
         */
        badgeText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lista di cosa contiene la confezione. Se vuoto, viene usato il default.
   */
  whatsInTheBox?:
    | {
        label?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  pipelineState?:
    | (
        | 'received'
        | 'eta_pending'
        | 'eta_confirmed'
        | 'in_production'
        | 'matching_pending'
        | 'matched'
        | 'preview_sent'
        | 'shipped'
        | 'delivered'
        | 'followup_done'
        | 'closed'
      )
    | null;
  customerEmail: string;
  customerName?: string | null;
  customerTelegramId?: string | null;
  customerLocale?: string | null;
  customerPhone?: string | null;
  total: number;
  shippingCost?: number | null;
  productionEtaDays?: number | null;
  lineItems:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  trackingNumber?: string | null;
  trackingCarrier?: string | null;
  shippingAddress?: {
    name?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  notes?: string | null;
  billingSameAsShipping?: boolean | null;
  billingCompanyName?: string | null;
  /**
   * IT12345678901
   */
  billingVatNumber?: string | null;
  /**
   * Es. 0000000
   */
  billingSdiCode?: string | null;
  billingAddress?: {
    name?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Foto dei fogli fisici abbinati a questo ordine.
   */
  sheetPhotos?:
    | {
        url: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  contentBlocks?:
    | {
        type: 'guide' | 'announcement' | 'offer' | 'tip';
        title: string;
        body: string;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        active?: boolean | null;
        expiresAt?: string | null;
        id?: string | null;
      }[]
    | null;
  source?: ('storefront' | 'woocommerce' | 'manual' | 'reseller') | null;
  pageToken?: string | null;
  revolutOrderId?: string | null;
  revolutStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  name?: string | null;
  telegramId?: string | null;
  telegramUsername?: string | null;
  preferredChannel?: ('telegram' | 'email') | null;
  /**
   * Es. IT, DE, FR
   */
  country?: string | null;
  totalOrders?: number | null;
  /**
   * Visibili solo ad Alessandro. Modificabili anche via Telegram.
   */
  notes?: string | null;
  tags?: ('tatuatore' | 'pmu' | 'studente' | 'professionista' | 'vip')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pro-members".
 */
export interface ProMember {
  id: number;
  vatNumber: string;
  businessName: string;
  contactName: string;
  email: string;
  telegramId?: string | null;
  discountCode: string;
  status: 'active' | 'suspended';
  channelInvited?: boolean | null;
  totalSpent?: number | null;
  orderCount?: number | null;
  notes?: string | null;
  joinedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  code: string;
  type: 'free_shipping' | 'percent_pro' | 'percent' | 'amount';
  /**
   * Es. 20 per il 20% di sconto
   */
  discountPercent?: number | null;
  /**
   * Es. 15 per €15 di sconto
   */
  discountAmount?: number | null;
  active?: boolean | null;
  /**
   * Lascia vuoto per codice senza scadenza
   */
  expiresAt?: string | null;
  proMember?: (number | null) | ProMember;
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * File e risorse per i clienti. Lascia "Cliente" vuoto per renderlo visibile a tutti.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-files".
 */
export interface CustomerFile {
  id: number;
  title: string;
  file: number | Media;
  /**
   * Lascia vuoto per rendere il file visibile a tutti i clienti registrati.
   */
  customer?: (number | null) | Customer;
  fileType: 'guide' | 'video' | 'resource';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sequenze di notifiche push automatiche per i clienti. Ogni sequenza ha un trigger e una lista di step con ritardo e testo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-sequences".
 */
export interface PushSequence {
  id: number;
  /**
   * Es. "Benvenuto all'attivazione", "Follow-up post-consegna"
   */
  name: string;
  /**
   * Quando parte questa sequenza.
   */
  trigger: 'on_subscribe' | 'on_order_shipped' | 'on_order_delivered' | 'manual';
  /**
   * Disattiva per mettere in pausa tutta la sequenza.
   */
  active?: boolean | null;
  /**
   * Ogni step viene inviato dopo il ritardo specificato dal trigger.
   */
  steps?:
    | {
        /**
         * Es. "welcome", "discount_48h", "review_7d". Non cambiare dopo il lancio.
         */
        step_key: string;
        /**
         * 0 = immediato. 48 = dopo 2 giorni. 168 = dopo 1 settimana.
         */
        delay_hours: number;
        title: string;
        body: string;
        /**
         * Path relativo. Es. "/account/ordini", "/it", "/account".
         */
        url?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configurazione offerta post-ordine. Crea un solo documento attivo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer-config".
 */
export interface OfferConfig {
  id: number;
  title: string;
  /**
   * Disattiva per non generare offerte sui nuovi ordini.
   */
  active?: boolean | null;
  /**
   * Il prodotto mostrato nella sezione Collezione dopo un ordine.
   */
  product: number | Product;
  /**
   * Ordini sotto questa cifra ricevono lo sconto minore, sopra quello maggiore.
   */
  threshold: number;
  discountBelow: number;
  discountAbove: number;
  validityHours: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pro-members';
        value: number | ProMember;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'customer-files';
        value: number | CustomerFile;
      } | null)
    | ({
        relationTo: 'push-sequences';
        value: number | PushSequence;
      } | null)
    | ({
        relationTo: 'offer-config';
        value: number | OfferConfig;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  section?: T;
  active?: T;
  limitedStock?: T;
  order?: T;
  madeToOrder?: T;
  productionDays?: T;
  shippingDays?: T;
  shortDescription?: T;
  description?: T;
  uniqueNote?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        video?: T;
        id?: T;
      };
  basePrice?: T;
  resellerVisible?: T;
  priceTiers?:
    | T
    | {
        minQty?: T;
        maxQty?: T;
        discountPercent?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        sku?: T;
        label?: T;
        price?: T;
        stockStatus?: T;
        limitedQty?: T;
        image?: T;
        description?: T;
        dimensions?: T;
        thicknessMm?: T;
        validCombinations?:
          | T
          | {
              texture?: T;
              colore?: T;
              spessore?: T;
              stencil?: T;
              id?: T;
            };
        id?: T;
      };
  attributes?:
    | T
    | {
        name?: T;
        label?: T;
        options?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  featureHighlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  usageSteps?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  components?: T;
  packs?:
    | T
    | {
        name?: T;
        quantity?: T;
        discountPercent?: T;
        badgeText?: T;
        id?: T;
      };
  whatsInTheBox?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  pipelineState?: T;
  customerEmail?: T;
  customerName?: T;
  customerTelegramId?: T;
  customerLocale?: T;
  customerPhone?: T;
  total?: T;
  shippingCost?: T;
  productionEtaDays?: T;
  lineItems?: T;
  trackingNumber?: T;
  trackingCarrier?: T;
  shippingAddress?:
    | T
    | {
        name?: T;
        address1?: T;
        address2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  notes?: T;
  billingSameAsShipping?: T;
  billingCompanyName?: T;
  billingVatNumber?: T;
  billingSdiCode?: T;
  billingAddress?:
    | T
    | {
        name?: T;
        address1?: T;
        address2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  sheetPhotos?:
    | T
    | {
        url?: T;
        caption?: T;
        id?: T;
      };
  contentBlocks?:
    | T
    | {
        type?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        active?: T;
        expiresAt?: T;
        id?: T;
      };
  source?: T;
  pageToken?: T;
  revolutOrderId?: T;
  revolutStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  telegramId?: T;
  telegramUsername?: T;
  preferredChannel?: T;
  country?: T;
  totalOrders?: T;
  notes?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pro-members_select".
 */
export interface ProMembersSelect<T extends boolean = true> {
  vatNumber?: T;
  businessName?: T;
  contactName?: T;
  email?: T;
  telegramId?: T;
  discountCode?: T;
  status?: T;
  channelInvited?: T;
  totalSpent?: T;
  orderCount?: T;
  notes?: T;
  joinedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  discountPercent?: T;
  discountAmount?: T;
  active?: T;
  expiresAt?: T;
  proMember?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-files_select".
 */
export interface CustomerFilesSelect<T extends boolean = true> {
  title?: T;
  file?: T;
  customer?: T;
  fileType?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-sequences_select".
 */
export interface PushSequencesSelect<T extends boolean = true> {
  name?: T;
  trigger?: T;
  active?: T;
  steps?:
    | T
    | {
        step_key?: T;
        delay_hours?: T;
        title?: T;
        body?: T;
        url?: T;
        active?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer-config_select".
 */
export interface OfferConfigSelect<T extends boolean = true> {
  title?: T;
  active?: T;
  product?: T;
  threshold?: T;
  discountBelow?: T;
  discountAbove?: T;
  validityHours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}